name: Build commands

on:
  push:
    branches: ["main"]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - app: cd
          - app: cp
          - app: dir
          - app: list
          - app: mk
          - app: rm

    steps:
      - uses: actions/checkout@v3

      - name: Run build
        run: |
          chmod +x build.sh
          ./build.sh ${{ matrix.config.app }}

      - name: Upload Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ matrix.config.app }}"
          files: |
            ${{ matrix.config.app }}.sapp